# Q3
*Work with Numpy*<br>
In this notebook you're going to work with the numpy library to solve the problems<br>
Please follow the instructions and hints provided for each cell

## Part A

In [1]:
import numpy as np

In [2]:
def create_matrix(n):
  """
  In this function you should create matrix in order of n*n with random numbers 
  in the [n, n+100) interval.

  see the bellow link:
    https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html

  Arguments:
    inputs:
      n: an integer describing the order of the matrix
    outputs:
      created matrix  
  """
  ##############################################
  ############ YOUR CODES GO HERE ##############
  matrix = np.random.randint(n, n+100, size=(n, n))
  ##############################################

  return matrix

In [3]:
"""
In this cell you should get the input n and create the matrix by calling the function
Then print the matrix
"""
##############################################
############ YOUR CODES GO HERE ##############
n = int(input())
matrix = create_matrix(n)
print(matrix)
# print matrix
##############################################

[[ 70  53  67  61  99  46  46]
 [ 67  56  93  77  96  63  88]
 [ 70  99  12  43  29  66  43]
 [ 36 104   7  84  15  78  82]
 [ 33   8   9  99  90  56  79]
 [ 11  35  34  11  97  42  73]
 [ 60  54   9  84  68  64  63]]


In [4]:
def count_digits(matrix):
  """
  In this function you should implement a routine to count the digits in the given matrix.

  Arguments:
    inputs:
      matrix: input matrix
    outputs:
      digits: a dictionary containing digits as its keys and the counted numbers as its value
  """

  ##############################################
  ############ YOUR CODES GO HERE ##############
  digits = {}
  for i in range(0,10):
    digits[i]=0
  rows=matrix.shape[0]
  cols=matrix.shape[1]
  for x in range(0,rows):
    for y in range(0,cols):                       
      findhasdigit=[int(digit) for digit in str(matrix[x,y])[::1]]
      for r in findhasdigit:            
        digits[r]+=1  
              
  
  ##############################################

  return digits


In [5]:
"""
In this cell call the implemented function and print the result
"""
##############################################
############ YOUR CODES GO HERE ##############
##############################################
print(count_digits(matrix))

{0: 5, 1: 8, 2: 4, 3: 12, 4: 11, 5: 6, 6: 16, 7: 11, 8: 8, 9: 14}


## Part B

In [22]:

#source:https://www.geeksforgeeks.org/print-matrix-in-zig-zag-fashion/
def traverse_matrix(matrix):
      
  """
  Traverse the input matrix in the given manner then print result

  Arguments:
    inputs:
      matrix: input matrix
    outputs
  """

  ##############################################
  ############ YOUR CODES GO HERE ##############
  ##############################################
  rows=matrix.shape[0]
  cols=matrix.shape[1]
  trav=[[] for i in range(0,rows+cols-1)]
  for x in range(0,rows):
    for y in range(0,cols):
      s=x+y
      if s%2==1:
        trav[s].append(matrix[x,y])
      else:
        trav[s].insert(0,matrix[x,y])
  for i in trav:
    for j in i:
      print(j)                
          
  

In [23]:
traverse_matrix(matrix)
#print output

70
53
67
70
56
67
61
93
99
36
33
104
12
77
99
46
96
43
7
8
11
60
35
9
84
29
63
46
88
66
15
99
34
54
9
11
90
78
43
82
56
97
84
68
42
79
73
64
63
