# Q4

## Part A

In [13]:
"""
Please define the mentioned matrices and the operations

consider the bellow links:
https://numpy.org/doc/stable/reference/generated/numpy.transpose.html

https://numpy.org/doc/stable/reference/generated/numpy.dot.html

"""

##############################################
############ YOUR CODES GO HERE ##############

##############################################

import numpy as np

matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
a=np.array([[1],[-1],[1]])
b=np.array([[1,5,6],[-1,4,3],[1,2,3]])
transformatrix=np.transpose(matrix)
multiplematrixes=np.dot(transformatrix,matrix)
reversematrix=np.linalg.inv(multiplematrixes)
multimatrix2=np.dot(reversematrix, transformatrix)
multimatrix3=np.dot(multimatrix2,a)
print(np.add(multimatrix3,matrix))


[[0.796875 1.796875 2.796875]
 [4.       5.       6.      ]
 [7.203125 8.203125 9.203125]]


## Part B

In [12]:
def window_sliding(A, B):

  """
  In this function you should implement the sliding window method

  Arguments:
    inputs:
      A: a matrix of 3*3 order for treating as the window
      B: a matrix of 5*5 order for treating as the input matrix
    outputs:
      res: resulting matrix of the sliding window 
  """

  ##############################################
  ############ YOUR CODES GO HERE ##############
  n=A.shape[0]
  m=B.shape[0]
  res = np.zeros(shape=(n-m+1, n-m+1))
  for row in range(0,n-m+1):
    for col in range(0,n-m+1):
      res[row,col]=muilti(B,A[row:row+m,col:col+m])           
  return res

def muilti(B,S):
  sum=0
  n=B.shape[0]
  for i in range(0,n):
    for j in range(0,n):
      sum+=B[i,j]*S[i,j]
  return sum    

In [13]:
import numpy as np
A = np.array([[1,1,1,1,1], [1,2,2,2,1] , [1,2,2,2,1] , [1,2,2,2,1] ,[1,1,1,1,1]])
B = np.array([[1,1,1], [1,-9,1], [1,1,1]])
print(window_sliding(A, B))

[[-7. -5. -7.]
 [-5. -2. -5.]
 [-7. -5. -7.]]
